name = "anastasia-labs/aiken-design-patterns"
version = "v1.4.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Implementations of common design patterns for Cardano smart contracts"

[repository]
user = "anastasia-labs"
project = "aiken-design-patterns"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "keyan-m/aiken-scott-utils"
version = "v1.4.0"
source = "github"

[config]
